# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnFOtegnY-n9bP3XeHzihKlqV3rvY1T0
"""

from numpy import flexible
import time
import re 
from collections import Counter
try:
    d = Counter()
    filePath = input('Путь к файлу: ')
    with open(filePath, 'r', encoding='utf8') as file:
        for line in file:
          d.update(line.strip(',.\n'))
        file.close()
        print(d)
        print("Время: " + str(time.process_time()))
except FileNotFoundError:
    print('Файл не обнаружен.')
    print("Время: " + str(time.process_time()))
except ValueError:
    print('Некорректное значение.')
    print("Время выполнения: " + str(time.process_time()))